In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [4]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2024,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2024,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2024,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2024,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2024,Liverpool

In [5]:
matches.shape

(1260, 27)

In [7]:
#2 seasons, 20 squads, 38 matches

2 * 20 * 38

1520

In [8]:
matches["team"].value_counts()

team
Liverpool                   64
Chelsea                     63
Everton                     63
Nottingham Forest           63
Crystal Palace              63
Brentford                   63
Manchester City             63
Wolverhampton Wanderers     63
Fulham                      63
West Ham United             63
Newcastle United            63
Brighton and Hove Albion    63
Manchester United           63
Tottenham Hotspur           63
Aston Villa                 63
Arsenal                     63
Bournemouth                 62
Leicester City              38
Leeds United                38
Southampton                 38
Luton Town                  25
Burnley                     25
Sheffield United            25
Name: count, dtype: int64

In [9]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-06,12:30,Premier League,Matchweek 1,Sat,Away,D,2.0,2.0,Fulham,...,Match Report,NaN,11.0,3.0,12.4,0.0,0,0,2023,Liverpool
2,2022-08-15,20:00,Premier League,Matchweek 2,Mon,Home,D,1.0,1.0,Crystal Palace,...,Match Report,NaN,24.0,4.0,17.4,0.0,0,0,2023,Liverpool
3,2022-08-22,20:00,Premier League,Matchweek 3,Mon,Away,L,1.0,2.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,14.4,0.0,0,0,2023,Liverpool
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,9.0,0.0,Bournemouth,...,Match Report,NaN,19.0,12.0,11.6,0.0,0,0,2023,Liverpool
5,2022-08-31,20:00,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,23.0,6.0,17.8,0.0,0,0,2023,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,2024-01-31,20:15,Premier League,Matchweek 22,Wed,Home,W,4.0,1.0,Chelsea,...,Match Report,NaN,27.0,13.0,19.9,2.0,0,1,2024,Liverpool
35,2024-02-04,16:30,Premier League,Matchweek 23,Sun,Away,L,1.0,3.0,Arsenal,...,Match Report,NaN,10.0,1.0,19.7,0.0,0,0,2024,Liverpool
36,2024-02-10,15:00,Premier League,Matchweek 24,Sat,Home,W,3.0,1.0,Burnley,...,Match Report,NaN,25.0,10.0,15.4,0.0,0,0,2024,Liverpool
37,2024-02-17,12:30,Premier League,Matchweek 25,Sat,Away,W,4.0,1.0,Brentford,...,Match Report,NaN,15.0,8.0,15.9,1.0,0,0,2024,Liverpool
38,2024-02-21,19:30,Premier League,Matchweek 26,Wed,Home,W,4.0,1.0,Luton Town,...,Match Report,NaN,29.0,13.0,16.9,0.0,0,0,2024,Liverpool

In [10]:
matches["round"].value_counts()

round
Matchweek 1     40
Matchweek 14    40
Matchweek 25    40
Matchweek 24    40
Matchweek 23    40
Matchweek 22    40
Matchweek 21    40
Matchweek 2     40
Matchweek 19    40
Matchweek 18    40
Matchweek 16    40
Matchweek 15    40
Matchweek 20    40
Matchweek 13    40
Matchweek 12    40
Matchweek 11    40
Matchweek 10    40
Matchweek 9     40
Matchweek 8     40
Matchweek 7     40
Matchweek 6     40
Matchweek 5     40
Matchweek 4     40
Matchweek 3     40
Matchweek 17    38
Matchweek 26    22
Matchweek 27    20
Matchweek 29    20
Matchweek 30    20
Matchweek 31    20
Matchweek 33    20
Matchweek 34    20
Matchweek 28    20
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 32    20
Matchweek 38    20
Name: count, dtype: int64

In [18]:
matches.dtypes

date             object
time             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [19]:
#deleted comp and notes

In [20]:
matches["date"] = pd.to_datetime(matches["date"])

In [ ]:
matches["target"] = (matches["result"] == "W").astype("int")